baseURL = 'https://h-tomo-tohoku.github.io/'
languageCode = 'ja-jp'
title = 'Tomomasa Hara'
theme = 'PaperMod'

[params]
  [params.homeInfoParams]
    Title = ''
  [[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/h-tomo-tohoku"

  [[params.socialIcons]]
    name = "Twitter"
    url = "https://x.com/tomomasa_hara"
